services:
  traefik:
    image: traefik:v3.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"        # trafic HTTP
      - "8080:8080"    # dashboard Traefik accessible sur le host:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - thyngo-network

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DOCKER_ENV: "true"
      VITE_HMR_HOST: "localhost"
      VITE_HMR_PORT: "5173"
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "1000"
    depends_on:
      - api
    ports:
      - "5173:5173"
    volumes:
      - ./dashboard/src:/app/src
      - ./dashboard/public:/app/public
      - ./dashboard/tsconfig.json:/app/tsconfig.json
      - ./dashboard/vite.config.ts:/app/vite.config.ts
      - ./dashboard/index.html:/app/index.html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.localhost`)"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.services.dashboard.loadbalancer.server.port=5173"
    networks:
      - thyngo-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DOCKER_ENV: "true"
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.localhost`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.cors-middleware.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors-middleware.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS,PATCH"
      - "traefik.http.middlewares.cors-middleware.headers.accesscontrolallowheaders=*"
      - "traefik.http.routers.api.middlewares=cors-middleware"
    networks:
      - thyngo-network

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: thyngo_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: thyngo_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U thyngo_user -d thyngo_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - thyngo-network

  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    labels:
      - "traefik.http.routers.adminer.rule=Host(`adminer.localhost`)"
    networks:
      - thyngo-network

volumes:
  pgdata:

networks:
  thyngo-network:
    driver: bridge
